### PR TITLE
Fix ident reads

### PR DESCRIPTION
**Pull request by matthavener**

### CODE REVIEW

**Comment by anmonteiro** [comment]
I think this is fine for the ident case but it now breaks when reading queries for which the join key is a link. See that case in the Om Next source: https://github.com/omcljs/om/blob/master/src/main/om/next/impl/parser.cljc#L290-L292

Can you rework the PR to also support that case? Otherwise it's looking great

**Comment by matthavener** [comment]
I totally agree, but the project (and therefore test suite) depends on om.next alpha47, which doesn't include the fix for unique idents here: https://github.com/omcljs/om/commit/7a71425c1992032258e352ed99e44eb6ceb1a6a7

Any suggestions on how to proceed? The parser could handle both the old and new behavior. Or the project could be updated to alpha49.

**Comment by anmonteiro** [comment]
The problem with upgrading to alpha48 is that the server-side rendering tests will fail (more context in #28). I'm happy to take a patch + test that was tested with alpha48 even though the PR doesn't bump the Om dep.

**Comment by matthavener** [comment]
Works for me. I've updated the PR with code that works against alpha48.

**Review by anmonteiro — APPROVED** [review]
I've updated master to work with alpha48 and retried building your PR, which now passes CI.

This looks great. Thanks for working on this!

**Pull request merged**
