### PR TITLE
COMPASSSUS-29: use current route's query in the callback to `send`

### LINKED ISSUE #29: Use current route's query if `send` doesn't pass one in the callback
This trips up new users who think responses will be normalized

### PR DESCRIPTION
**Pull request by anmonteiro**
fixes #29

### CODE REVIEW

**Comment by anmonteiro** [comment]
Looking for feedback on this one. Does anyone see a reason not to establish this sensible default?

**Comment by matthavener** [comment]
:+1:

**Comment by cmcfarlen** [comment]
https://gist.github.com/cmcfarlen/c68b5050a14e8e910ff1001f5fc1eeb2

This is how we currently default the query to the current route query.  I'm not sure if the assumptions we made are always valid, but they are for our apps.

I think your PR is very sensible as a default since in the read case its what you want anyway and doesn't prevent any normal use of cb.

I added our send fn to the gist as well as a use case example.

**Comment by anmonteiro** [comment]
I think we don't even need to wrap the send function. Since we wrap merge in any case we can just overwrite the query there. I also believe we want to do this before `migrate`, as `merge` is called with the query before it gets to `migrate`

**Comment by Peeja** [comment]
IMO it's poor form not to pass the query to the callback in the first place, so I suppose I don't have much to say about the default. Is there a good use case for not passing the query back? Do you ever not have it?

**Comment by cmcfarlen** [comment]
You don't have the query for remote mutates.  `remotes` will have shape similar to:

```
{:remote [('some/mutate {:param1 "foo" :param2 "bar"})]}
```

But but when calling the callback, you have to have knowledge about the shape of any novelty from the server to give an appropriate query.  In practice (in our case), it ends up matching either the current route query or some child query of the route query.

**Comment by anmonteiro** [comment]
Thanks for all the feedback, I ended up finding a weird edge case in `compassus-merge` too

**Pull request merged**
