### PR TITLE
mixin data available to wrap-render

### PR DESCRIPTION
**Pull request by stuarth**
Feel free to disregard if this isn't the approach you had in mind! 😄

### CODE REVIEW

**Comment by anmonteiro** [comment]
Hah, definitely something I forgot to add :-)
I don't like merging mixin-data with regular props though.
I was thinking we could provide a `mixin-data` function in the style of `om.next/get-computed`.

Wanna take a stab at that?

**Comment by stuarth** [comment]
Sure, happy to! Traveling this weekend, so it'll be a couple days. Definitely don't wait if it's not convenient for you

**Comment by anmonteiro** [comment]
OK so I actually changed the way wrapper queries work. see #10 for context.
Closing this as it doesn't apply anymore.

Thanks anyway!

**Comment by stuarth** [comment]
Great, this approach looks good!

**Pull request closed without merging**
