### PR TITLE
add render-to-str test

### PR DESCRIPTION
**Pull request by nha**

### CODE REVIEW

**Comment by anmonteiro** [comment]
Not sure why the CircleCI tests aren't running...

**Comment by anmonteiro** [comment]
@nha tests are failing because something weird happens when including `om.dom` and running the tests in Node.js.

Can you fix this to only include `om.dom` in the `:clj` branch?

**Review by anmonteiro — APPROVED** [review]

**Comment by anmonteiro** [comment]
Thanks!

**Comment by nha** [comment]
Thank you :)

**Pull request merged**
